/* SQLiteDB.c generated by valac 0.10.0, the Vala compiler
 * generated from SQLiteDB.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <sqlite3.h>
#include <stdlib.h>
#include <string.h>
#include <gmodule.h>
#include <stdio.h>


#define IRC_TYPE_SQ_LITE_DB (irc_sq_lite_db_get_type ())
#define IRC_SQ_LITE_DB(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), IRC_TYPE_SQ_LITE_DB, IRCSQLiteDB))
#define IRC_SQ_LITE_DB_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), IRC_TYPE_SQ_LITE_DB, IRCSQLiteDBClass))
#define IRC_IS_SQ_LITE_DB(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), IRC_TYPE_SQ_LITE_DB))
#define IRC_IS_SQ_LITE_DB_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), IRC_TYPE_SQ_LITE_DB))
#define IRC_SQ_LITE_DB_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), IRC_TYPE_SQ_LITE_DB, IRCSQLiteDBClass))

typedef struct _IRCSQLiteDB IRCSQLiteDB;
typedef struct _IRCSQLiteDBClass IRCSQLiteDBClass;
typedef struct _IRCSQLiteDBPrivate IRCSQLiteDBPrivate;
#define _sqlite3_close0(var) ((var == NULL) ? NULL : (var = (sqlite3_close (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

#define IRC_TYPE_MESSAGE (irc_message_get_type ())
#define IRC_MESSAGE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), IRC_TYPE_MESSAGE, IRCMessage))
#define IRC_MESSAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), IRC_TYPE_MESSAGE, IRCMessageClass))
#define IRC_IS_MESSAGE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), IRC_TYPE_MESSAGE))
#define IRC_IS_MESSAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), IRC_TYPE_MESSAGE))
#define IRC_MESSAGE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), IRC_TYPE_MESSAGE, IRCMessageClass))

typedef struct _IRCMessage IRCMessage;
typedef struct _IRCMessageClass IRCMessageClass;
#define _sqlite3_finalize0(var) ((var == NULL) ? NULL : (var = (sqlite3_finalize (var), NULL)))
#define _irc_message_unref0(var) ((var == NULL) ? NULL : (var = (irc_message_unref (var), NULL)))
#define _g_date_time_unref0(var) ((var == NULL) ? NULL : (var = (g_date_time_unref (var), NULL)))
#define __g_list_free_irc_message_unref0(var) ((var == NULL) ? NULL : (var = (_g_list_free_irc_message_unref (var), NULL)))

struct _IRCSQLiteDB {
	GObject parent_instance;
	IRCSQLiteDBPrivate * priv;
};

struct _IRCSQLiteDBClass {
	GObjectClass parent_class;
};


extern sqlite3* irc_sq_lite_db_DataBase;
sqlite3* irc_sq_lite_db_DataBase = NULL;
static gpointer irc_sq_lite_db_parent_class = NULL;

GType irc_sq_lite_db_get_type (void) G_GNUC_CONST;
enum  {
	IRC_SQ_LITE_DB_DUMMY_PROPERTY
};
#define IRC_SQ_LITE_DB__path (_tmp0_ = g_module_build_path (g_getenv ("PWD"), "MyLogData.db"))
IRCSQLiteDB* irc_sq_lite_db_new (void);
IRCSQLiteDB* irc_sq_lite_db_construct (GType object_type);
void irc_sq_lite_db_CreateDB (void);
gpointer irc_message_ref (gpointer instance);
void irc_message_unref (gpointer instance);
GParamSpec* irc_param_spec_message (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void irc_value_set_message (GValue* value, gpointer v_object);
void irc_value_take_message (GValue* value, gpointer v_object);
gpointer irc_value_get_message (const GValue* value);
GType irc_message_get_type (void) G_GNUC_CONST;
void irc_sq_lite_db_Insert (IRCMessage* message);
const char* irc_message_get_Username (IRCMessage* self);
const char* irc_message_get_MessageContent (IRCMessage* self);
const char* irc_message_get_Channel (IRCMessage* self);
const char* irc_message_get_Server (IRCMessage* self);
gint64 irc_message_get_UnixTime (IRCMessage* self);
void irc_sq_lite_db_ShowLog (const char* username);
IRCMessage* irc_message_new (const char* username, const char* message, const char* channel, const char* server, GDateTime* time);
IRCMessage* irc_message_construct (GType object_type, const char* username, const char* message, const char* channel, const char* server, GDateTime* time);
static void _g_list_free_irc_message_unref (GList* self);
static void irc_sq_lite_db_finalize (GObject* obj);



IRCSQLiteDB* irc_sq_lite_db_construct (GType object_type) {
	IRCSQLiteDB * self;
	self = (IRCSQLiteDB*) g_object_new (object_type, NULL);
	return self;
}


IRCSQLiteDB* irc_sq_lite_db_new (void) {
	return irc_sq_lite_db_construct (IRC_TYPE_SQ_LITE_DB);
}


static gint _sqlite3_exec (sqlite3* self, const char* sql, sqlite3_callback sqlite3_callback, void* sqlite3_callback_target, char** errmsg) {
	gint result = 0;
	const char* sqlite_errmsg;
	gint ec;
	g_return_val_if_fail (self != NULL, 0);
	g_return_val_if_fail (sql != NULL, 0);
	if (errmsg != NULL) {
		*errmsg = NULL;
	}
	sqlite_errmsg = NULL;
	ec = sqlite3_exec (self, sql, sqlite3_callback, sqlite3_callback_target, (char**) (&sqlite_errmsg));
	if ((errmsg) != NULL) {
		char* _tmp0_;
		*errmsg = (_tmp0_ = g_strdup (sqlite_errmsg), _g_free0 (*errmsg), _tmp0_);
	}
	sqlite3_free ((void*) sqlite_errmsg);
	result = ec;
	return result;
}


void irc_sq_lite_db_CreateDB (void) {
	sqlite3* _tmp0_ = NULL;
	gint _tmp1_;
	sqlite3* _tmp2_;
	gint _result_;
	char* createLog;
	fprintf (stdout, "%s\n", IRC_SQ_LITE_DB__path);
	_result_ = (_tmp1_ = sqlite3_open (IRC_SQ_LITE_DB__path, &_tmp0_), irc_sq_lite_db_DataBase = (_tmp2_ = _tmp0_, _sqlite3_close0 (irc_sq_lite_db_DataBase), _tmp2_), _tmp1_);
	createLog = g_strdup ("CREATE TABLE MyLogData (Username TEXT, Message TEXT NULL, Channel TEXT" \
", Server TEXT, Timestamp INTEGER)");
	if (_result_ == SQLITE_OK) {
		_sqlite3_exec (irc_sq_lite_db_DataBase, createLog, NULL, NULL, NULL);
	}
	_g_free0 (createLog);
}


void irc_sq_lite_db_Insert (IRCMessage* message) {
	char* commandText;
	sqlite3_stmt* statement;
	sqlite3_stmt* _tmp0_ = NULL;
	sqlite3_stmt* _tmp1_;
	g_return_if_fail (message != NULL);
	if (irc_sq_lite_db_DataBase == NULL) {
		fprintf (stdout, "Datenbank wird erstellt!\n");
		irc_sq_lite_db_CreateDB ();
	}
	commandText = g_strdup ("INSERT INTO MyLogData (Username, Message, Channel, Server, Timestamp) " \
"VALUES (@1, @2, @3, @4, @5)");
	statement = NULL;
	sqlite3_prepare_v2 (irc_sq_lite_db_DataBase, commandText, -1, &_tmp0_, NULL);
	statement = (_tmp1_ = _tmp0_, _sqlite3_finalize0 (statement), _tmp1_);
	sqlite3_bind_text (statement, 1, g_strdup (irc_message_get_Username (message)), -1, g_free);
	sqlite3_bind_text (statement, 2, g_strdup (irc_message_get_MessageContent (message)), -1, g_free);
	sqlite3_bind_text (statement, 3, g_strdup (irc_message_get_Channel (message)), -1, g_free);
	sqlite3_bind_text (statement, 4, g_strdup (irc_message_get_Server (message)), -1, g_free);
	sqlite3_bind_int64 (statement, 5, irc_message_get_UnixTime (message));
	sqlite3_step (statement);
	_sqlite3_finalize0 (statement);
	_g_free0 (commandText);
}


static gpointer _irc_message_ref0 (gpointer self) {
	return self ? irc_message_ref (self) : NULL;
}


static void _g_list_free_irc_message_unref (GList* self) {
	g_list_foreach (self, (GFunc) irc_message_unref, NULL);
	g_list_free (self);
}


void irc_sq_lite_db_ShowLog (const char* username) {
	sqlite3* _tmp0_ = NULL;
	sqlite3* _tmp1_;
	char* commandText;
	sqlite3_stmt* statement;
	sqlite3_stmt* _tmp2_ = NULL;
	sqlite3_stmt* _tmp3_;
	gint _result_;
	GList* results;
	g_return_if_fail (username != NULL);
	fprintf (stdout, "Datenbank wird ausgelesen!\n");
	sqlite3_open (IRC_SQ_LITE_DB__path, &_tmp0_);
	irc_sq_lite_db_DataBase = (_tmp1_ = _tmp0_, _sqlite3_close0 (irc_sq_lite_db_DataBase), _tmp1_);
	commandText = g_strdup ("SELECT * FROM MyLogData WHERE Username = @1 ORDER BY Timestamp DESC LI" \
"MIT 10");
	statement = NULL;
	sqlite3_prepare_v2 (irc_sq_lite_db_DataBase, commandText, -1, &_tmp2_, NULL);
	statement = (_tmp3_ = _tmp2_, _sqlite3_finalize0 (statement), _tmp3_);
	sqlite3_bind_text (statement, 1, g_strdup (username), -1, g_free);
	_result_ = sqlite3_step (statement);
	results = NULL;
	while (TRUE) {
		char* Username;
		char* MessageContent;
		char* Channel;
		char* Server;
		GDateTime* FromUnixTime;
		IRCMessage* msg;
		if (!(_result_ == SQLITE_ROW)) {
			break;
		}
		Username = g_strdup (sqlite3_column_text (statement, 0));
		MessageContent = g_strdup (sqlite3_column_text (statement, 1));
		Channel = g_strdup (sqlite3_column_text (statement, 2));
		Server = g_strdup (sqlite3_column_text (statement, 3));
		FromUnixTime = g_date_time_new_from_unix_local (g_ascii_strtoll (sqlite3_column_text (statement, 4), NULL, 0));
		msg = irc_message_new (Username, MessageContent, Channel, Server, FromUnixTime);
		results = g_list_append (results, _irc_message_ref0 (msg));
		_result_ = sqlite3_step (statement);
		_irc_message_unref0 (msg);
		_g_date_time_unref0 (FromUnixTime);
		_g_free0 (Server);
		_g_free0 (Channel);
		_g_free0 (MessageContent);
		_g_free0 (Username);
	}
	{
		GList* r_collection;
		GList* r_it;
		r_collection = results;
		for (r_it = r_collection; r_it != NULL; r_it = r_it->next) {
			IRCMessage* r;
			r = _irc_message_ref0 ((IRCMessage*) r_it->data);
			{
				fprintf (stdout, "%s\n", irc_message_get_MessageContent (r));
				_irc_message_unref0 (r);
			}
		}
	}
	__g_list_free_irc_message_unref0 (results);
	_sqlite3_finalize0 (statement);
	_g_free0 (commandText);
}


static void irc_sq_lite_db_class_init (IRCSQLiteDBClass * klass) {
	irc_sq_lite_db_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->finalize = irc_sq_lite_db_finalize;
}


static void irc_sq_lite_db_instance_init (IRCSQLiteDB * self) {
}


static void irc_sq_lite_db_finalize (GObject* obj) {
	IRCSQLiteDB * self;
	self = IRC_SQ_LITE_DB (obj);
	G_OBJECT_CLASS (irc_sq_lite_db_parent_class)->finalize (obj);
}


GType irc_sq_lite_db_get_type (void) {
	static volatile gsize irc_sq_lite_db_type_id__volatile = 0;
	if (g_once_init_enter (&irc_sq_lite_db_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (IRCSQLiteDBClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) irc_sq_lite_db_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (IRCSQLiteDB), 0, (GInstanceInitFunc) irc_sq_lite_db_instance_init, NULL };
		GType irc_sq_lite_db_type_id;
		irc_sq_lite_db_type_id = g_type_register_static (G_TYPE_OBJECT, "IRCSQLiteDB", &g_define_type_info, 0);
		g_once_init_leave (&irc_sq_lite_db_type_id__volatile, irc_sq_lite_db_type_id);
	}
	return irc_sq_lite_db_type_id__volatile;
}




